name: secrets workflow test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
      - uses: actions/checkout@v2
      - run: echo "checked out code"

      - name: print the secret
      - run: echo "the secret is ${{secret.MY_SECRET}}"

